import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link, useNavigate, useLocation } from 'react-router-dom';
import { Search, Menu, X, Globe, Facebook, Instagram, Youtube, Twitter, ArrowRight, ChevronLeft, ChevronRight, Scale, HandCoins, Store, Clock3, Wheat, UserRound, Map, Sprout, BadgeIndianRupee, LogOut, LayoutDashboard } from 'lucide-react';
import './index.css';

const images={hero:['https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1800&q=85','https://images.unsplash.com/photo-1523742810-3f8f7b17d9b8?auto=format&fit=crop&w=1800&q=85','https://images.unsplash.com/photo-1530507629858-e4977d30e9e0?auto=format&fit=crop&w=1800&q=85'],farmer:'https://images.unsplash.com/photo-1592982537447-6f2a6a0a7c65?auto=format&fit=crop&w=600&q=80',field:'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1200&q=80'};
const services=[{title:'Fair Pricing',text:'Know the right price for every harvest.',icon:HandCoins,path:'/services'},{title:'Transparent Weighing',text:'Accurate weighing you can trust.',icon:Scale,path:'/services'},{title:'Direct Market Access',text:'Connect directly with verified buyers.',icon:Store,path:'/services'},{title:'कम प्रतीक्षा समय',text:'Faster procurement, quicker payments.',icon:Clock3,path:'/services'}];
const testimonials=[['“Thanks to Kisaan Setu, I now have direct access to the market, ensuring a fair price for my produce. The weighing process is transparent and trustworthy.”','Rajesh Kumar','Wheat farmer, Haryana'],['“My payment reaches my bank account on time. The centre team and the app have made selling my paddy simple.”','Savitri Devi','Paddy farmer, Punjab'],['“I can see MSP and procurement updates before travelling to the mandi. It saves my family a whole day.”','Mohan Singh','Rice farmer, Uttar Pradesh']];

function Logo(){return <Link className="logo" to="/"><div className="logo-mark"><Wheat size={27}/></div><div><strong>KISAAN <span>SETU</span></strong><small>सही तौल सही दाम, सीधे किसान के नाम</small></div></Link>}
function SocialIcons(){return <div className="socials"><Facebook size={16}/><Twitter size={16}/><Instagram size={16}/><Youtube size={16}/></div>}
function SearchBar(){const [q,setQ]=useState('');return <form className="search" onSubmit={e=>{e.preventDefault();alert(q?`Searching for ${q}`:'Please enter a search term')}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search here..."/><button aria-label="Search"><Search size={17}/></button></form>}
function Header(){const [open,setOpen]=useState(false);const location=useLocation();return <header><div className="topbar"><Logo/><div className="header-tools"><SearchBar/><select aria-label="Language"><option>English</option><option>हिन्दी</option></select><SocialIcons/></div><nav className={open?'open':''}>{[['Home','/'],['Services','/services'],['About Us','/about'],['Contact','/contact']].map(([n,p])=><Link className={location.pathname===p?'active':''} to={p} onClick={()=>setOpen(false)} key={p}>{n}</Link>)}<Link className="login-btn" to="/login">LOGIN <ArrowRight size={16}/></Link></nav><button className="menu-btn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>}
function Hero(){const [slide,setSlide]=useState(0);React.useEffect(()=>{const t=setInterval(()=>setSlide(s=>(s+1)%3),6000);return()=>clearInterval(t)},[]);const copy=[['Empowering','Farmers Directly'],['Fair trade starts','with trust'],['Your harvest,','your right price']];return <section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(3,32,22,.82),rgba(3,32,22,.2)),url(${images.hero[slide]})`}}><div className="hero-copy"><p className="eyebrow">KISAAN SETU • SIH 2026</p><h1>{copy[slide][0]}<br/><span>{copy[slide][1]}</span></h1><p className="hindi">बिल्कुल सीधे किसानों से जुड़ाव</p><Link className="primary-btn" to="/services">Explore services <ArrowRight size={18}/></Link></div><div className="hero-arrows"><button onClick={()=>setSlide((slide+2)%3)}><ChevronLeft/></button><button onClick={()=>setSlide((slide+1)%3)}><ChevronRight/></button></div><div className="dots">{copy.map((_,i)=><button className={i===slide?'selected':''} onClick={()=>setSlide(i)} key={i}/>)}</div></section>}
function ServiceCard({service}){const Icon=service.icon;return <Link to={service.path} className="service-card"><div className="service-icon"><Icon size={25}/></div><div><h3>{service.title}</h3><p>{service.text}</p></div><ArrowRight className="card-arrow" size={17}/></Link>}
function Services(){return <section className="services-wrap"><div className="section-heading"><p className="eyebrow green">WHAT WE DO</p><h2>Our Services</h2><p>Fair, transparent and direct — everything your harvest deserves.</p></div><div className="service-grid">{services.map((s,i)=><ServiceCard service={s} key={i}/>)}</div></section>}
function Testimonials(){const [i,setI]=useState(0);const t=testimonials[i];return <section className="testimonial-section"><div className="testimonial-photo" style={{backgroundImage:`url(${images.farmer})`}}><span>खेती से समृद्धि</span></div><div className="testimonial-content"><p className="eyebrow green">VOICES OF TRUST</p><h2>Testimonials</h2><p className="quote">{t[0]}</p><div className="person"><div className="avatar">{t[1][0]}</div><div><b>{t[1]}</b><small>{t[2]}</small></div></div><div className="testimonial-controls"><button onClick={()=>setI((i+testimonials.length-1)%testimonials.length)}><ChevronLeft/></button><div className="mini-dots">{testimonials.map((_,x)=><i className={x===i?'on':''} key={x}/>)}</div><button onClick={()=>setI((i+1)%testimonials.length)}><ChevronRight/></button></div></div></section>}
function Footer(){return <footer><div><Logo/><p>Bridging the gap between farmers and fair markets.</p></div><div className="footer-search"><SearchBar/><select><option>English</option><option>हिन्दी</option></select></div><SocialIcons/><div className="copyright">© 2026 Kisaan Setu. Built for Bharat.</div></footer>}
function Home(){return <><Header/><main><Hero/><Services/><Testimonials/><section className="field-strip" style={{backgroundImage:`url(${images.field})`}}><div><p className="eyebrow">GROW WITH CONFIDENCE</p><h2>जब किसान आगे बढ़ेगा,<br/>भारत आगे बढ़ेगा।</h2><Link className="primary-btn" to="/login">Join Kisaan Setu <ArrowRight size={18}/></Link></div></section></main><Footer/></>}
function Shell({children,title}){const navigate=useNavigate();return <><Header/><div className="page-shell"><p className="eyebrow green">KISAAN SETU</p><h1>{title}</h1>{children}</div><Footer/></>}
function ServicesPage(){return <Shell title="Services built around you"><p className="lead">We make every step from field to market simpler, fairer and faster.</p><div className="detail-grid">{services.map((s,i)=><article className="detail-card" key={i}><ServiceCard service={s}/><p>Get reliable information, verified procurement and a direct connection to the market. Our field teams and digital tools work together so that your hard work gets its true value.</p><button className="text-btn">Learn more <ArrowRight size={16}/></button></article>)}</div></Shell>}
function About(){return <Shell title="A bridge for Bharat's farmers"><div className="about-grid"><img src={images.farmer}/><div><h2>Technology that respects the soil.</h2><p>Kisaan Setu is a digital-first procurement platform created for SIH 2026. We connect farmers, procurement centres and buyers in one transparent ecosystem.</p><p>From live MSP information to transparent weighing and timely digital payments, we put choice and confidence back in the farmer's hands.</p><div className="stats"><b>100%<small>Transparent</small></b><b>Direct<small>Market access</small></b><b>24×7<small>Updates</small></b></div></div></div></Shell>}
function Contact(){return <Shell title="We are here to help"><div className="contact-grid"><form className="contact-form" onSubmit={e=>{e.preventDefault();alert('Thanks! Our support team will contact you soon.')}}><input required placeholder="Your name"/><input required type="tel" placeholder="Mobile number"/><input required type="email" placeholder="Email address"/><textarea required placeholder="How can we help?" rows="5"/><button className="primary-btn">Send message <ArrowRight size={17}/></button></form><div className="contact-info"><h2>Talk to Kisaan Setu</h2><p>Our support team is ready to help with registration, procurement and payments.</p><b>📞 1800-123-4567</b><b>✉ support@kisaansetu.in</b><b>📍 Krishi Bhawan, New Delhi — 110001</b></div></div></Shell>}
function Login(){const navigate=useNavigate();const [sent,setSent]=useState(false);return <div className="login-page"><div className="login-art"><Logo/><div><p className="eyebrow">KISAAN SETU</p><h1>आपकी मेहनत,<br/><span>आपका हक।</span></h1><p>Fair markets. Transparent processes. Better livelihoods.</p></div></div><div className="login-form"><Link to="/" className="back">← Back to home</Link><div className="login-box"><div className="mobile-logo"><Logo/></div><p className="eyebrow green">WELCOME BACK</p><h2>Farmer Login</h2><p>Enter your registered mobile number to continue.</p><label>Farmer ID / Mobile Number<input type="tel" placeholder="e.g. 98765 43210"/></label>{sent&&<label>One-time password (OTP)<input placeholder="Enter 6-digit OTP" maxLength="6"/></label>}<button className="primary-btn full" onClick={()=>sent?navigate('/farmer/dashboard'):setSent(true)}>{sent?'Verify & continue':'Send OTP'} <ArrowRight size={17}/></button><select><option>English</option><option>हिन्दी</option></select></div></div></div>}
const dashCards=[['Land area','12.5 Acres',Map],['Current crop','Wheat • Rabi',Sprout],['Current MSP','₹2,275 / Quintal',BadgeIndianRupee],['Procurement centre','Sonipat Centre',Store],['Total quantity','84 Quintals',Wheat],['Expected payment','₹1,91,100',HandCoins]];
function Dashboard(){const navigate=useNavigate();return <div className="dashboard"><aside><Logo/><p className="side-label">FARMER PORTAL</p>{[['Overview','/farmer/dashboard',LayoutDashboard],['My Profile','/farmer/profile',UserRound],['My Land','/farmer/land',Map],['Crops','/farmer/crops',Sprout],['MSP Rates','/farmer/msp',BadgeIndianRupee],['Procurement','/farmer/procurement',Store],['Payments','/farmer/payment',HandCoins]].map(([n,p,I])=><Link className={location.pathname===p?'sel':''} to={p} key={p}><I size={18}/>{n}</Link>)}<button onClick={()=>navigate('/login')} className="logout"><LogOut size={18}/>Log out</button></aside><div className="dash-main"><header className="dash-top"><div><p className="eyebrow green">FARMER PORTAL / OVERVIEW</p><h1>Namaste, Rajesh 👋</h1></div><div className="dash-user"><div className="avatar">R</div><span>Rajesh Kumar<br/><small>KS-2026-10482</small></span></div></header><div className="dash-banner"><div><p className="eyebrow">NEXT STEP</p><h2>Your wheat is ready for procurement.</h2><p>Slot confirmed for 22 March 2026 at Sonipat Centre.</p></div><button className="primary-btn" onClick={()=>navigate('/farmer/procurement')}>View details <ArrowRight size={17}/></button></div><div className="dash-grid">{dashCards.map(([n,v,I])=><div className="dash-card" key={n}><div className="dash-icon"><I size={21}/></div><small>{n}</small><strong>{v}</strong></div>)}</div><div className="dash-bottom"><div className="panel"><div className="panel-head"><h3>Payment overview</h3><span className="status">On track</span></div><div className="chart"><i style={{height:'35%'}}/><i style={{height:'52%'}}/><i style={{height:'45%'}}/><i style={{height:'68%'}}/><i style={{height:'62%'}}/><i style={{height:'88%'}}/></div><div className="chart-labels"><span>Oct</span><span>Nov</span><span>Dec</span><span>Jan</span><span>Feb</span><span>Mar</span></div></div><div className="panel status-panel"><h3>Procurement status</h3><div className="steps"><b className="done">✓ <span>Registration verified</span></b><b className="done">✓ <span>Slot booked</span></b><b className="current">3 <span>Weighing & quality check</span></b><b>4 <span>Payment credited</span></b></div></div></div></div></div>}
function Detail({title,children}){return <div className="dashboard"><aside><Logo/><p className="side-label">FARMER PORTAL</p><Link to="/farmer/dashboard"><LayoutDashboard size={18}/>Overview</Link><Link className="sel" to="#"><UserRound size={18}/>{title}</Link><Link to="/farmer/payment"><HandCoins size={18}/>Payments</Link><button onClick={()=>location.href='/login'} className="logout"><LogOut size={18}/>Log out</button></aside><div className="dash-main"><header className="dash-top"><div><p className="eyebrow green">FARMER PORTAL</p><h1>{title}</h1></div><Link to="/farmer/dashboard" className="back">← Dashboard</Link></header><div className="detail-panel">{children}</div></div></div>}
function Admin(){return <Shell title="Admin command centre"><div className="dash-grid">{[['Registered farmers','12,840'],['Active centres','64'],['Pending procurements','218'],['Payments processed','₹4.8 Cr']].map(x=><div className="dash-card" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div><div className="detail-panel"><h2>Centre activity</h2><p>All procurement centres are operating normally. 96% of farmer payments are within the 48-hour service promise.</p></div></Shell>}
function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/services" element={<ServicesPage/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="/login" element={<Login/>}/><Route path="/farmer/dashboard" element={<Dashboard/>}/><Route path="/admin" element={<Admin/>}/>{[['profile','My Profile'],['land','My Land'],['crops','My Crops'],['msp','MSP Rates'],['procurement','Procurement'],['payment','Payments']].map(([p,t])=><Route key={p} path={`/farmer/${p}`} element={<Detail title={t}><h2>{t}</h2><p>Your {t.toLowerCase()} information is verified and up to date.</p><div className="info-list"><b>Rajesh Kumar</b><span>Updated 18 March 2026</span><span>All records are securely stored and available to you anytime.</span></div></Detail>}/>)}<Route path="/procurement-centre" element={<Detail title="Procurement centres"><h2>Find a centre near you</h2><p>Sonipat Centre · 4.2 km away · Open today 8:00 AM – 6:00 PM</p></Detail>}/></Routes>}

createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
